[IMG ID]
CodePage=1252
LblCoding=9
ID=58000090
Name=Venezuela 090
Elevation=M
Preprocess=F
TreSize=5000
TreMargin=0.00000
RgnLimit=1024
POIIndex=Y
POINumberFirst=N
POIZipFirst=N
MG=Y
Routing=Y
Copyright=www.gpsve.net
Levels=5
Level0=24
Level1=22
Level2=20
Level3=19
Level4=18
Zoom0=0
Zoom1=1
Zoom2=2
Zoom3=3
Zoom4=4
[END-IMG ID]

[POI]
Label=Vía #551
Data0=(11.78698,-69.96070)
Type=0x1604
EndLevel=3
[END]

