//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GpsYv.ManejadorDeMapa.Interfase.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Recursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recursos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GpsYv.ManejadorDeMapa.Interfase.Properties.Recursos", typeof(Recursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licencia.htm.
        /// </summary>
        internal static string ArchivoLicencia {
            get {
                return ResourceManager.GetString("ArchivoLicencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clase de Ruta.
        /// </summary>
        internal static string ClaseDeRuta {
            get {
                return ResourceManager.GetString("ClaseDeRuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manejador de Mapa.
        /// </summary>
        internal static string DescripciónDelEjecutable {
            get {
                return ResourceManager.GetString("DescripciónDelEjecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idéntico.
        /// </summary>
        internal static string Idéntico {
            get {
                return ResourceManager.GetString("Idéntico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignorar que el PDI tipo Ciudad no tenga campos City=Y o CitiIdx.
        /// </summary>
        internal static string InterfaseDePdisConErroresMenuIgnorarPdiCiudadNoCamposCityOCityIdx {
            get {
                return ResourceManager.GetString("InterfaseDePdisConErroresMenuIgnorarPdiCiudadNoCamposCityOCityIdx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignorar que el PDI no tenga coordenadas a nivel 0.
        /// </summary>
        internal static string InterfaseDePdisConErroresMenuIgnorarPdiNoCoordenadasANivel0 {
            get {
                return ResourceManager.GetString("InterfaseDePdisConErroresMenuIgnorarPdiNoCoordenadasANivel0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta seguro(a) que quiere ignorar que los {0} PDI seleccionados no tengan campos City=Y o CityIdx a pesar que sean tipo Ciudad?.
        /// </summary>
        internal static string InterfaseDePdisConErroresPreguntaIgnorarPdiCiudadNoCamposCityOCityIdx {
            get {
                return ResourceManager.GetString("InterfaseDePdisConErroresPreguntaIgnorarPdiCiudadNoCamposCityOCityIdx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Está seguro(a) que quiere Ignorar los {0} PDIs seleccionados si no tienen coordenadas a nivel 0?.
        /// </summary>
        internal static string InterfaseDePdisConErroresPreguntaIgnorarPdiNoCoordenadasANivel0 {
            get {
                return ResourceManager.GetString("InterfaseDePdisConErroresPreguntaIgnorarPdiNoCoordenadasANivel0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitud.
        /// </summary>
        internal static string Latitud {
            get {
                return ResourceManager.GetString("Latitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Límite de Velocidad.
        /// </summary>
        internal static string LímiteDeVelocidad {
            get {
                return ResourceManager.GetString("LímiteDeVelocidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitud.
        /// </summary>
        internal static string Longitud {
            get {
                return ResourceManager.GetString("Longitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ Hay {0} elementos seleccionados ].
        /// </summary>
        internal static string MenuEditorDeElementosPrimeraLinea {
            get {
                return ResourceManager.GetString("MenuEditorDeElementosPrimeraLinea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar archivo de PDIs para localización de Vía(s).
        /// </summary>
        internal static string MenuEditorDeViasGuardarArchivo {
            get {
                return ResourceManager.GetString("MenuEditorDeViasGuardarArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muy Parecido.
        /// </summary>
        internal static string MuyParecido {
            get {
                return ResourceManager.GetString("MuyParecido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetros.
        /// </summary>
        internal static string Parámetros {
            get {
                return ResourceManager.GetString("Parámetros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parecido.
        /// </summary>
        internal static string Parecido {
            get {
                return ResourceManager.GetString("Parecido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La búsqueda de palabras similares usa la librería  &quot;Ternary Search Tree Implementation for C#&quot; de Jonathan de Halleux (http://www.codeproject.com/KB/recipes/tst.aspx)
        ///
        ///Usando la clase PolygonF de Joel: http://www.developingfor.net/free-code/polygonf.
        /// </summary>
        internal static string VentanaDeAcercaDescripción {
            get {
                return ResourceManager.GetString("VentanaDeAcercaDescripción", resourceCulture);
            }
        }
    }
}
